### ISSUE TITLE
Fastest way to coinjoin on Ubuntu

### ISSUE THREAD

**Issue by clay-v** [clay-v/joinMarketDocs#1]
## Payout: 750k sats (0.0075 btc)

[Guide file](https://github.com/clay-v/joinMarketDocs/blob/master/docs/users/from-zero-to-coinjoin.md)

We'd like a guide on the fastest way to make a first coinjoin on a desktop. We'd like to have the user to be able to go from zero to be able to make a payment in Joinmarket in the fastest way possible.

1. Install Virtual Box
[01 Ubuntu Node Box - Ubuntu Virtual Machine & Familiarisation](https://www.youtube.com/watch?v=BIrL1lNsnJQ&list=PLCRbH-IWlcW17JxQ4mdv9DwSMJZlvUOle)
- [ ] Optimize for minimum requirements necessary in terms of storage, ram and cpu

2. Install [Joininbox](https://github.com/openoms/joininbox#set-up-joininbox-on-linux) - it was brought to my attention by @openoms that Joininbox can do a lot of the hevy lifting and can work on Debian / Ubuntu Linux VM as well.
- [ ] Download and verify signature
- [ ] Edit joinmarket.cfg
- [ ] Tumbler
- [ ] Single coinjoin
[12 Ubuntu Node Box - JoinMarket](https://www.youtube.com/watch?v=zTCC86IUzWo&list=PLCRbH-IWlcW17JxQ4mdv9DwSMJZlvUOle&index=12)
[How To Use JoinMarket - Bitcoin Privacy Software](https://www.youtube.com/watch?v=9COdlsh4inY)
[Joinmarket documentation](https://github.com/JoinMarket-Org/joinmarket-clientserver/tree/master/docs)

**Comment by clay-v** [comment]
@openoms

Everything went great except for the Qt. I go through the menu and get to the screen with the command to open the GUI on Linux
`ssh -X joinmarket@192.168.1.241 joinmarket-clientserver/jmvenv/bin/python joinmarket-clientserver/scripts/joinmarket-qt.py`

I changed it to `/home/joinmarket/joinmarket-clientserver/jmvenv/bin/python /home/joinmarket/joinmarket-clientserver/scripts/joinmarket-qt.py` since it's the same computer and I get

	No protocol specified
	qt.qpa.xcb: could not connect to display :0
	qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
	This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

	Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

	Aborted (core dumped)

**Comment by openoms** [comment]
what works for me on Debian Buster desktop:
* switch to the `joinmarket` user desktop
* start the terminal
* exit the joininbox menu
* run (in `(jmvenv) joinmarket@X1:~/joinmarket-clientserver/scripts$`):
* `python joinmarket-qt.py`

![Screenshot from 2021-06-14 16-19-37](https://user-images.githubusercontent.com/43343391/121916903-7891ac80-cd2c-11eb-8687-687870fb1d9e.png)

The instructions can be updated to explain these steps in a VM even from the menu.

**Comment by clay-v** [comment]
Yeah, that didn't work for me. I tried some things that may have messed it up. I may have to restart. I'll get back to you.

**Comment by openoms** [comment]
By switching user I meant to use the User menu, switch user in Linux and log in with the `joinmarket` user, not just switching the terminal.
Otherwise the desktop environment will get into those permission problems.

**Comment by clay-v** [comment]
Ok, that was the solution: switch user in the desktop, not just the terminal.
Man Joininbox is way better than what I thought it was. This setup just broke all espectations I had. I was used to interact with it through Raspberry Pies so my mind was elsewhere.

I don't have much time left today (and in general) but I hope to be able to attract enough people and reward them for their contribution.

**Comment by clay-v** [comment]
I am pretty much done with the Ubuntu guide.
